import type { FileExplorerNode } from './types.ts';

export const mockFileTree: FileExplorerNode[] = [
  {
    id: 'public',
    name: 'public',
    type: 'folder',
    path: 'public',
    children: [
      { id: 'public-favicon', name: 'favicon.ico', type: 'file', path: 'public/favicon.ico' },
      { id: 'public-placeholder', name: 'placeholder.svg', type: 'file', path: 'public/placeholder.svg' },
      { id: 'public-robots', name: 'robots.txt', type: 'file', path: 'public/robots.txt' },
    ],
  },
  {
    id: 'src',
    name: 'src',
    type: 'folder',
    path: 'src',
    children: [
      {
        id: 'src-components',
        name: 'components',
        type: 'folder',
        path: 'src/components',
        children: [],
      },
      {
        id: 'src-hooks',
        name: 'hooks',
        type: 'folder',
        path: 'src/hooks',
        children: [],
      },
      {
        id: 'src-lib',
        name: 'lib',
        type: 'folder',
        path: 'src/lib',
        children: [],
      },
      {
        id: 'src-pages',
        name: 'pages',
        type: 'folder',
        path: 'src/pages',
        children: [],
      },
      {
        id: 'src-test',
        name: 'test',
        type: 'folder',
        path: 'src/test',
        children: [],
      },
      { id: 'src-App.css', name: 'App.css', type: 'file', path: 'src/App.css' },
      { id: 'src-App.tsx', name: 'App.tsx', type: 'file', path: 'src/App.tsx' },
      { id: 'src-index.css', name: 'index.css', type: 'file', path: 'src/index.css' },
      { id: 'src-main.tsx', name: 'main.tsx', type: 'file', path: 'src/main.tsx' },
      { id: 'src-vite-env.d.ts', name: 'vite-env.d.ts', type: 'file', path: 'src/vite-env.d.ts' },
    ],
  },
  { id: 'root-gitignore', name: '.gitignore', type: 'file', path: '.gitignore' },
  { id: 'root-components.json', name: 'components.json', type: 'file', path: 'components.json' },
  { id: 'root-eslint.config.js', name: 'eslint.config.js', type: 'file', path: 'eslint.config.js' },
  { id: 'root-index.html', name: 'index.html', type: 'file', path: 'index.html' },
  { id: 'root-package.json', name: 'package.json', type: 'file', path: 'package.json' },
  { id: 'root-postcss.config.js', name: 'postcss.config.js', type: 'file', path: 'postcss.config.js' },
  { id: 'root-README.md', name: 'README.md', type: 'file', path: 'README.md' },
  { id: 'root-tsconfig.app.json', name: 'tsconfig.app.json', type: 'file', path: 'tsconfig.app.json' },
  { id: 'root-tsconfig.json', name: 'tsconfig.json', type: 'file', path: 'tsconfig.json' },
  { id: 'root-tsconfig.node.json', name: 'tsconfig.node.json', type: 'file', path: 'tsconfig.node.json' },
  { id: 'root-vite.config.ts', name: 'vite.config.ts', type: 'file', path: 'vite.config.ts' },
  { id: 'root-vitest.config.ts', name: 'vitest.config.ts', type: 'file', path: 'vitest.config.ts' },
];
