# Studio Docker Workflow
# ======================
#
# PURPOSE:
# Builds and publishes the loopstack-studio Docker image.
# Called by release workflows.
#
# INPUTS:
# - version: Version tag for the image
#
# MANUAL TRIGGER:
# Can rebuild images without republishing to npm.

name: Studio Docker

on:
  workflow_call:
    inputs:
      version:
        description: 'Version to tag the image with'
        required: true
        type: string

    secrets:
      GITHUB_TOKEN:
        required: true
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (leave empty to read from package.json)'
        required: false
        type: string

permissions:
  contents: read
  packages: write

jobs:
  publish:
    name: 'Build & Publish'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Determine version
        id: version
        run: |
          if [ -n "${{ inputs.version }}" ]; then
            echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=$(node -p "require('./frontend/loopstack-studio/package.json').version")" >> $GITHUB_OUTPUT
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker Metadata
        id: meta-stable
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/loopstack-ai/loopstack-studio
          tags: |
            type=semver,pattern={{version}},value=${{ steps.version.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.version.outputs.version }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend/loopstack-studio
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-stable.outputs.tags }}
          labels: ${{ steps.meta-stable.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create summary
        run: |
          echo "## Studio Docker Image Published ðŸ³" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Version:** ${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
