version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: infra-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - monorepo-network
  postgres:
    image: postgres
    container_name: infra-postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monorepo-network
  adminer:
    image: adminer
    container_name: infra-adminer
    restart: always
    ports:
      - '8081:8080'
    networks:
      - monorepo-network
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: infra-chroma
    volumes:
      - chroma_data:/chroma/.chroma/index
    ports:
      - '8082:8000'

networks:
  monorepo-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  chroma_data:
    driver: local
  redis-data:
    driver: local