import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type { StarlightUserConfig } from '@astrojs/starlight/types';

const REPO_ROOT = path.resolve(fileURLToPath(new URL('..', import.meta.url)), '..');

/** The `title` from a markdown file's frontmatter, or null if it has none. */
function frontmatterTitle(file: string): string | null {
  const head = fs.readFileSync(file, 'utf-8').slice(0, 2000);
  const match = head.match(/^---\n[\s\S]*?^title:\s*(.+?)\s*$/m);
  return match ? match[1].replace(/^['"]|['"]$/g, '') : null;
}

/**
 * Sidebar entries for a set of pages, listed explicitly.
 *
 * Starlight's `autogenerate` cannot be used for any of these: it matches entries by file path with
 * the `src/content/docs/` prefix stripped, and these files live outside that directory, so every
 * autogenerated group came out empty. Reading the directory here keeps new packages and regenerated
 * API pages appearing without a config edit, which is what autogenerate was there for.
 */
function entriesFrom(
  dir: string,
  routePrefix: string,
  options: { readme?: boolean; stripLabelPrefix?: string } = {},
): { label: string; slug: string }[] {
  const base = path.join(REPO_ROOT, dir);
  if (!fs.existsSync(base)) return [];

  const entries = fs
    .readdirSync(base, { withFileTypes: true })
    .flatMap((entry) => {
      const file = options.readme
        ? path.join(base, entry.name, 'README.md')
        : path.join(base, entry.name);
      if (options.readme ? !entry.isDirectory() : !entry.isFile() || !entry.name.endsWith('.md')) return [];
      if (!fs.existsSync(file)) return [];

      const name = options.readme ? entry.name : entry.name.replace(/\.md$/, '');
      let label = frontmatterTitle(file) ?? name;
      if (options.stripLabelPrefix && label.startsWith(options.stripLabelPrefix)) {
        label = label.slice(options.stripLabelPrefix.length);
      }
      return [{ label, slug: `${routePrefix}/${name}` }];
    });

  return entries.sort((a, b) => a.label.localeCompare(b.label));
}


/**
 * The docs navigation. Section titles come from `docs/docs.json`; the page order within each
 * section is explicit here so adding a doc does not silently reorder the sidebar.
 * `skills/` is built and searchable but deliberately unlisted.
 */
export const sidebar: StarlightUserConfig['sidebar'] = [
  {
    label: 'Learn',
    items: [
      'docs/learn/introduction',
      'docs/learn/core-concepts',
      'docs/learn/capabilities',
      'docs/learn/architecture',
      'docs/learn/workflow-engine',
      'docs/learn/document-store',
      'docs/learn/studio',
    ],
  },
  {
    label: 'Build',
    items: [
      'docs/build/getting-started',
      'docs/build/add-to-existing-app',
      'docs/build/best-practices',
      {
        label: 'Fundamentals',
        items: [
          'docs/build/fundamentals/workflows',
          'docs/build/fundamentals/tools',
          'docs/build/fundamentals/documents',
          'docs/build/fundamentals/modules',
          'docs/build/fundamentals/studio-config',
        ],
      },
      {
        label: 'AI',
        items: [
          'docs/build/ai/text-generation',
          'docs/build/ai/structured-output',
          'docs/build/ai/tool-calling',
          'docs/build/ai/chat-flows',
          'docs/build/ai/agent-workflows',
          'docs/build/ai/llm-providers',
          'docs/build/ai/usage-tracking',
        ],
      },
      {
        label: 'Patterns',
        items: [
          'docs/build/patterns/human-in-the-loop',
          'docs/build/patterns/sub-workflows',
          'docs/build/patterns/dynamic-routing',
          'docs/build/patterns/state-management',
          'docs/build/patterns/error-handling',
          'docs/build/patterns/templates',
        ],
      },
      {
        label: 'Integrations',
        items: [
          'docs/build/integrations/oauth',
          'docs/build/integrations/sandbox',
          'docs/build/integrations/secrets',
          { label: 'Scheduling & Programmatic Execution', slug: 'docs/build/integrations/programmatic-execution' },
        ],
      },
      'docs/build/testing',
      'docs/build/testing-methodology',
      'docs/build/troubleshooting',
    ],
  },
  {
    label: 'Tutorials',
    items: ['docs/tutorials/hitl-approval-workflow', 'docs/tutorials/chat-agent-with-tools'],
  },
  {
    label: 'Extend',
    items: [
      'docs/extend/llm-providers',
      'docs/extend/oauth-providers',
      'docs/extend/features',
      'docs/extend/tool-interceptors',
      'docs/extend/custom-bootstrap',
    ],
  },
  {
    label: 'Reference',
    items: [
      'docs/reference/imports',
      'docs/reference/configuration',
      'docs/reference/workflow-yaml',
      'docs/reference/document-yaml',
      'docs/reference/cli',
      'docs/reference/client',
      'docs/reference/react',
      'docs/reference/prompt-selection',
      {
        label: 'API Reference',
        collapsed: true,
        items: entriesFrom('docs/reference/api', 'docs/reference/api', { stripLabelPrefix: 'API: ' }),
      },
    ],
  },
  {
    label: 'Registry',
    items: [
      { label: 'Overview', slug: 'docs/registry' },
      {
        label: 'Features',
        collapsed: true,
        items: entriesFrom('registry/features', 'docs/registry/features', { readme: true }),
      },
      {
        label: 'Examples',
        collapsed: true,
        items: entriesFrom('registry/examples', 'docs/registry/examples', { readme: true }),
      },
    ],
  },
  { label: 'llms.txt', link: '/llms.txt', attrs: { target: '_blank' } },
];
