/* tslint:disable */
/* eslint-disable */
/**
 * Plan a meal Api
 * An api for the loopstack plan a meal demo
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';


/**
 * ApiV1ProcessorApi - axios parameter creator
 * @export
 */
export const ApiV1ProcessorApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Run a project
         * @param {string} projectId The ID of the project
         * @param {object} body Run Payload
         * @param {boolean} [force] Force run the project
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        processorControllerRunProject: async (projectId: string, body: object, force?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'projectId' is not null or undefined
            assertParamExists('processorControllerRunProject', 'projectId', projectId)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('processorControllerRunProject', 'body', body)
            const localVarPath = `/api/v1/processor/run/{projectId}`
                .replace(`{${"projectId"}}`, encodeURIComponent(String(projectId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (force !== undefined) {
                localVarQueryParameter['force'] = force;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ApiV1ProcessorApi - functional programming interface
 * @export
 */
export const ApiV1ProcessorApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ApiV1ProcessorApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Run a project
         * @param {string} projectId The ID of the project
         * @param {object} body Run Payload
         * @param {boolean} [force] Force run the project
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async processorControllerRunProject(projectId: string, body: object, force?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.processorControllerRunProject(projectId, body, force, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ApiV1ProcessorApi.processorControllerRunProject']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ApiV1ProcessorApi - factory interface
 * @export
 */
export const ApiV1ProcessorApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ApiV1ProcessorApiFp(configuration)
    return {
        /**
         * 
         * @summary Run a project
         * @param {ApiV1ProcessorApiProcessorControllerRunProjectRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        processorControllerRunProject(requestParameters: ApiV1ProcessorApiProcessorControllerRunProjectRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.processorControllerRunProject(requestParameters.projectId, requestParameters.body, requestParameters.force, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ApiV1ProcessorApi - interface
 * @export
 * @interface ApiV1ProcessorApi
 */
export interface ApiV1ProcessorApiInterface {
    /**
     * 
     * @summary Run a project
     * @param {ApiV1ProcessorApiProcessorControllerRunProjectRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiV1ProcessorApiInterface
     */
    processorControllerRunProject(requestParameters: ApiV1ProcessorApiProcessorControllerRunProjectRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;

}

/**
 * Request parameters for processorControllerRunProject operation in ApiV1ProcessorApi.
 * @export
 * @interface ApiV1ProcessorApiProcessorControllerRunProjectRequest
 */
export interface ApiV1ProcessorApiProcessorControllerRunProjectRequest {
    /**
     * The ID of the project
     * @type {string}
     * @memberof ApiV1ProcessorApiProcessorControllerRunProject
     */
    readonly projectId: string

    /**
     * Run Payload
     * @type {object}
     * @memberof ApiV1ProcessorApiProcessorControllerRunProject
     */
    readonly body: object

    /**
     * Force run the project
     * @type {boolean}
     * @memberof ApiV1ProcessorApiProcessorControllerRunProject
     */
    readonly force?: boolean
}

/**
 * ApiV1ProcessorApi - object-oriented interface
 * @export
 * @class ApiV1ProcessorApi
 * @extends {BaseAPI}
 */
export class ApiV1ProcessorApi extends BaseAPI implements ApiV1ProcessorApiInterface {
    /**
     * 
     * @summary Run a project
     * @param {ApiV1ProcessorApiProcessorControllerRunProjectRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiV1ProcessorApi
     */
    public processorControllerRunProject(requestParameters: ApiV1ProcessorApiProcessorControllerRunProjectRequest, options?: RawAxiosRequestConfig) {
        return ApiV1ProcessorApiFp(this.configuration).processorControllerRunProject(requestParameters.projectId, requestParameters.body, requestParameters.force, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ApiV1ProjectsApi - axios parameter creator
 * @export
 */
export const ApiV1ProjectsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new project
         * @param {object} body Project data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectControllerCreateProject: async (body: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('projectControllerCreateProject', 'body', body)
            const localVarPath = `/api/v1/projects`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a project by ID
         * @param {string} id The ID of the project
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectControllerDeleteProject: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('projectControllerDeleteProject', 'id', id)
            const localVarPath = `/api/v1/projects/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a project by ID
         * @param {string} id The ID of the project
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectControllerGetProjectById: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('projectControllerGetProjectById', 'id', id)
            const localVarPath = `/api/v1/projects/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Retrieve projects with filters, sorting, and pagination
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectControllerSearchProjects: async (body: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('projectControllerSearchProjects', 'body', body)
            const localVarPath = `/api/v1/projects/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a project by ID
         * @param {string} id The ID of the project
         * @param {object} body Updated project data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectControllerUpdateProject: async (id: string, body: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('projectControllerUpdateProject', 'id', id)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('projectControllerUpdateProject', 'body', body)
            const localVarPath = `/api/v1/projects/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ApiV1ProjectsApi - functional programming interface
 * @export
 */
export const ApiV1ProjectsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ApiV1ProjectsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new project
         * @param {object} body Project data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async projectControllerCreateProject(body: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.projectControllerCreateProject(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ApiV1ProjectsApi.projectControllerCreateProject']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a project by ID
         * @param {string} id The ID of the project
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async projectControllerDeleteProject(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.projectControllerDeleteProject(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ApiV1ProjectsApi.projectControllerDeleteProject']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a project by ID
         * @param {string} id The ID of the project
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async projectControllerGetProjectById(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.projectControllerGetProjectById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ApiV1ProjectsApi.projectControllerGetProjectById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Retrieve projects with filters, sorting, and pagination
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async projectControllerSearchProjects(body: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.projectControllerSearchProjects(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ApiV1ProjectsApi.projectControllerSearchProjects']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a project by ID
         * @param {string} id The ID of the project
         * @param {object} body Updated project data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async projectControllerUpdateProject(id: string, body: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.projectControllerUpdateProject(id, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ApiV1ProjectsApi.projectControllerUpdateProject']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ApiV1ProjectsApi - factory interface
 * @export
 */
export const ApiV1ProjectsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ApiV1ProjectsApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new project
         * @param {ApiV1ProjectsApiProjectControllerCreateProjectRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectControllerCreateProject(requestParameters: ApiV1ProjectsApiProjectControllerCreateProjectRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.projectControllerCreateProject(requestParameters.body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a project by ID
         * @param {ApiV1ProjectsApiProjectControllerDeleteProjectRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectControllerDeleteProject(requestParameters: ApiV1ProjectsApiProjectControllerDeleteProjectRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.projectControllerDeleteProject(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a project by ID
         * @param {ApiV1ProjectsApiProjectControllerGetProjectByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectControllerGetProjectById(requestParameters: ApiV1ProjectsApiProjectControllerGetProjectByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.projectControllerGetProjectById(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Retrieve projects with filters, sorting, and pagination
         * @param {ApiV1ProjectsApiProjectControllerSearchProjectsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectControllerSearchProjects(requestParameters: ApiV1ProjectsApiProjectControllerSearchProjectsRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.projectControllerSearchProjects(requestParameters.body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a project by ID
         * @param {ApiV1ProjectsApiProjectControllerUpdateProjectRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectControllerUpdateProject(requestParameters: ApiV1ProjectsApiProjectControllerUpdateProjectRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.projectControllerUpdateProject(requestParameters.id, requestParameters.body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ApiV1ProjectsApi - interface
 * @export
 * @interface ApiV1ProjectsApi
 */
export interface ApiV1ProjectsApiInterface {
    /**
     * 
     * @summary Create a new project
     * @param {ApiV1ProjectsApiProjectControllerCreateProjectRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiV1ProjectsApiInterface
     */
    projectControllerCreateProject(requestParameters: ApiV1ProjectsApiProjectControllerCreateProjectRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Delete a project by ID
     * @param {ApiV1ProjectsApiProjectControllerDeleteProjectRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiV1ProjectsApiInterface
     */
    projectControllerDeleteProject(requestParameters: ApiV1ProjectsApiProjectControllerDeleteProjectRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get a project by ID
     * @param {ApiV1ProjectsApiProjectControllerGetProjectByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiV1ProjectsApiInterface
     */
    projectControllerGetProjectById(requestParameters: ApiV1ProjectsApiProjectControllerGetProjectByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Retrieve projects with filters, sorting, and pagination
     * @param {ApiV1ProjectsApiProjectControllerSearchProjectsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiV1ProjectsApiInterface
     */
    projectControllerSearchProjects(requestParameters: ApiV1ProjectsApiProjectControllerSearchProjectsRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Update a project by ID
     * @param {ApiV1ProjectsApiProjectControllerUpdateProjectRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiV1ProjectsApiInterface
     */
    projectControllerUpdateProject(requestParameters: ApiV1ProjectsApiProjectControllerUpdateProjectRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;

}

/**
 * Request parameters for projectControllerCreateProject operation in ApiV1ProjectsApi.
 * @export
 * @interface ApiV1ProjectsApiProjectControllerCreateProjectRequest
 */
export interface ApiV1ProjectsApiProjectControllerCreateProjectRequest {
    /**
     * Project data
     * @type {object}
     * @memberof ApiV1ProjectsApiProjectControllerCreateProject
     */
    readonly body: object
}

/**
 * Request parameters for projectControllerDeleteProject operation in ApiV1ProjectsApi.
 * @export
 * @interface ApiV1ProjectsApiProjectControllerDeleteProjectRequest
 */
export interface ApiV1ProjectsApiProjectControllerDeleteProjectRequest {
    /**
     * The ID of the project
     * @type {string}
     * @memberof ApiV1ProjectsApiProjectControllerDeleteProject
     */
    readonly id: string
}

/**
 * Request parameters for projectControllerGetProjectById operation in ApiV1ProjectsApi.
 * @export
 * @interface ApiV1ProjectsApiProjectControllerGetProjectByIdRequest
 */
export interface ApiV1ProjectsApiProjectControllerGetProjectByIdRequest {
    /**
     * The ID of the project
     * @type {string}
     * @memberof ApiV1ProjectsApiProjectControllerGetProjectById
     */
    readonly id: string
}

/**
 * Request parameters for projectControllerSearchProjects operation in ApiV1ProjectsApi.
 * @export
 * @interface ApiV1ProjectsApiProjectControllerSearchProjectsRequest
 */
export interface ApiV1ProjectsApiProjectControllerSearchProjectsRequest {
    /**
     * 
     * @type {object}
     * @memberof ApiV1ProjectsApiProjectControllerSearchProjects
     */
    readonly body: object
}

/**
 * Request parameters for projectControllerUpdateProject operation in ApiV1ProjectsApi.
 * @export
 * @interface ApiV1ProjectsApiProjectControllerUpdateProjectRequest
 */
export interface ApiV1ProjectsApiProjectControllerUpdateProjectRequest {
    /**
     * The ID of the project
     * @type {string}
     * @memberof ApiV1ProjectsApiProjectControllerUpdateProject
     */
    readonly id: string

    /**
     * Updated project data
     * @type {object}
     * @memberof ApiV1ProjectsApiProjectControllerUpdateProject
     */
    readonly body: object
}

/**
 * ApiV1ProjectsApi - object-oriented interface
 * @export
 * @class ApiV1ProjectsApi
 * @extends {BaseAPI}
 */
export class ApiV1ProjectsApi extends BaseAPI implements ApiV1ProjectsApiInterface {
    /**
     * 
     * @summary Create a new project
     * @param {ApiV1ProjectsApiProjectControllerCreateProjectRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiV1ProjectsApi
     */
    public projectControllerCreateProject(requestParameters: ApiV1ProjectsApiProjectControllerCreateProjectRequest, options?: RawAxiosRequestConfig) {
        return ApiV1ProjectsApiFp(this.configuration).projectControllerCreateProject(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a project by ID
     * @param {ApiV1ProjectsApiProjectControllerDeleteProjectRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiV1ProjectsApi
     */
    public projectControllerDeleteProject(requestParameters: ApiV1ProjectsApiProjectControllerDeleteProjectRequest, options?: RawAxiosRequestConfig) {
        return ApiV1ProjectsApiFp(this.configuration).projectControllerDeleteProject(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a project by ID
     * @param {ApiV1ProjectsApiProjectControllerGetProjectByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiV1ProjectsApi
     */
    public projectControllerGetProjectById(requestParameters: ApiV1ProjectsApiProjectControllerGetProjectByIdRequest, options?: RawAxiosRequestConfig) {
        return ApiV1ProjectsApiFp(this.configuration).projectControllerGetProjectById(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Retrieve projects with filters, sorting, and pagination
     * @param {ApiV1ProjectsApiProjectControllerSearchProjectsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiV1ProjectsApi
     */
    public projectControllerSearchProjects(requestParameters: ApiV1ProjectsApiProjectControllerSearchProjectsRequest, options?: RawAxiosRequestConfig) {
        return ApiV1ProjectsApiFp(this.configuration).projectControllerSearchProjects(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a project by ID
     * @param {ApiV1ProjectsApiProjectControllerUpdateProjectRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiV1ProjectsApi
     */
    public projectControllerUpdateProject(requestParameters: ApiV1ProjectsApiProjectControllerUpdateProjectRequest, options?: RawAxiosRequestConfig) {
        return ApiV1ProjectsApiFp(this.configuration).projectControllerUpdateProject(requestParameters.id, requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ApiV1WorkspacesApi - axios parameter creator
 * @export
 */
export const ApiV1WorkspacesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new workspace
         * @param {object} body Workspace data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        workspaceControllerCreateWorkspace: async (body: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('workspaceControllerCreateWorkspace', 'body', body)
            const localVarPath = `/api/v1/workspaces`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a workspace by ID
         * @param {string} id The ID of the workspace
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        workspaceControllerDeleteWorkspace: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('workspaceControllerDeleteWorkspace', 'id', id)
            const localVarPath = `/api/v1/workspaces/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all workspaces for the user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        workspaceControllerGetAllWorkspaces: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/workspaces`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a workspace by ID
         * @param {string} id The ID of the workspace
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        workspaceControllerGetWorkspaceById: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('workspaceControllerGetWorkspaceById', 'id', id)
            const localVarPath = `/api/v1/workspaces/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a workspace by ID
         * @param {string} id The ID of the workspace
         * @param {object} body Updated workspace data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        workspaceControllerUpdateWorkspace: async (id: string, body: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('workspaceControllerUpdateWorkspace', 'id', id)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('workspaceControllerUpdateWorkspace', 'body', body)
            const localVarPath = `/api/v1/workspaces/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ApiV1WorkspacesApi - functional programming interface
 * @export
 */
export const ApiV1WorkspacesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ApiV1WorkspacesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new workspace
         * @param {object} body Workspace data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async workspaceControllerCreateWorkspace(body: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.workspaceControllerCreateWorkspace(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ApiV1WorkspacesApi.workspaceControllerCreateWorkspace']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a workspace by ID
         * @param {string} id The ID of the workspace
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async workspaceControllerDeleteWorkspace(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.workspaceControllerDeleteWorkspace(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ApiV1WorkspacesApi.workspaceControllerDeleteWorkspace']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all workspaces for the user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async workspaceControllerGetAllWorkspaces(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.workspaceControllerGetAllWorkspaces(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ApiV1WorkspacesApi.workspaceControllerGetAllWorkspaces']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a workspace by ID
         * @param {string} id The ID of the workspace
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async workspaceControllerGetWorkspaceById(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.workspaceControllerGetWorkspaceById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ApiV1WorkspacesApi.workspaceControllerGetWorkspaceById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a workspace by ID
         * @param {string} id The ID of the workspace
         * @param {object} body Updated workspace data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async workspaceControllerUpdateWorkspace(id: string, body: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.workspaceControllerUpdateWorkspace(id, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ApiV1WorkspacesApi.workspaceControllerUpdateWorkspace']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ApiV1WorkspacesApi - factory interface
 * @export
 */
export const ApiV1WorkspacesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ApiV1WorkspacesApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new workspace
         * @param {ApiV1WorkspacesApiWorkspaceControllerCreateWorkspaceRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        workspaceControllerCreateWorkspace(requestParameters: ApiV1WorkspacesApiWorkspaceControllerCreateWorkspaceRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.workspaceControllerCreateWorkspace(requestParameters.body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a workspace by ID
         * @param {ApiV1WorkspacesApiWorkspaceControllerDeleteWorkspaceRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        workspaceControllerDeleteWorkspace(requestParameters: ApiV1WorkspacesApiWorkspaceControllerDeleteWorkspaceRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.workspaceControllerDeleteWorkspace(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all workspaces for the user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        workspaceControllerGetAllWorkspaces(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.workspaceControllerGetAllWorkspaces(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a workspace by ID
         * @param {ApiV1WorkspacesApiWorkspaceControllerGetWorkspaceByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        workspaceControllerGetWorkspaceById(requestParameters: ApiV1WorkspacesApiWorkspaceControllerGetWorkspaceByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.workspaceControllerGetWorkspaceById(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a workspace by ID
         * @param {ApiV1WorkspacesApiWorkspaceControllerUpdateWorkspaceRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        workspaceControllerUpdateWorkspace(requestParameters: ApiV1WorkspacesApiWorkspaceControllerUpdateWorkspaceRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.workspaceControllerUpdateWorkspace(requestParameters.id, requestParameters.body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ApiV1WorkspacesApi - interface
 * @export
 * @interface ApiV1WorkspacesApi
 */
export interface ApiV1WorkspacesApiInterface {
    /**
     * 
     * @summary Create a new workspace
     * @param {ApiV1WorkspacesApiWorkspaceControllerCreateWorkspaceRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiV1WorkspacesApiInterface
     */
    workspaceControllerCreateWorkspace(requestParameters: ApiV1WorkspacesApiWorkspaceControllerCreateWorkspaceRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Delete a workspace by ID
     * @param {ApiV1WorkspacesApiWorkspaceControllerDeleteWorkspaceRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiV1WorkspacesApiInterface
     */
    workspaceControllerDeleteWorkspace(requestParameters: ApiV1WorkspacesApiWorkspaceControllerDeleteWorkspaceRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get all workspaces for the user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiV1WorkspacesApiInterface
     */
    workspaceControllerGetAllWorkspaces(options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get a workspace by ID
     * @param {ApiV1WorkspacesApiWorkspaceControllerGetWorkspaceByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiV1WorkspacesApiInterface
     */
    workspaceControllerGetWorkspaceById(requestParameters: ApiV1WorkspacesApiWorkspaceControllerGetWorkspaceByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Update a workspace by ID
     * @param {ApiV1WorkspacesApiWorkspaceControllerUpdateWorkspaceRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiV1WorkspacesApiInterface
     */
    workspaceControllerUpdateWorkspace(requestParameters: ApiV1WorkspacesApiWorkspaceControllerUpdateWorkspaceRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;

}

/**
 * Request parameters for workspaceControllerCreateWorkspace operation in ApiV1WorkspacesApi.
 * @export
 * @interface ApiV1WorkspacesApiWorkspaceControllerCreateWorkspaceRequest
 */
export interface ApiV1WorkspacesApiWorkspaceControllerCreateWorkspaceRequest {
    /**
     * Workspace data
     * @type {object}
     * @memberof ApiV1WorkspacesApiWorkspaceControllerCreateWorkspace
     */
    readonly body: object
}

/**
 * Request parameters for workspaceControllerDeleteWorkspace operation in ApiV1WorkspacesApi.
 * @export
 * @interface ApiV1WorkspacesApiWorkspaceControllerDeleteWorkspaceRequest
 */
export interface ApiV1WorkspacesApiWorkspaceControllerDeleteWorkspaceRequest {
    /**
     * The ID of the workspace
     * @type {string}
     * @memberof ApiV1WorkspacesApiWorkspaceControllerDeleteWorkspace
     */
    readonly id: string
}

/**
 * Request parameters for workspaceControllerGetWorkspaceById operation in ApiV1WorkspacesApi.
 * @export
 * @interface ApiV1WorkspacesApiWorkspaceControllerGetWorkspaceByIdRequest
 */
export interface ApiV1WorkspacesApiWorkspaceControllerGetWorkspaceByIdRequest {
    /**
     * The ID of the workspace
     * @type {string}
     * @memberof ApiV1WorkspacesApiWorkspaceControllerGetWorkspaceById
     */
    readonly id: string
}

/**
 * Request parameters for workspaceControllerUpdateWorkspace operation in ApiV1WorkspacesApi.
 * @export
 * @interface ApiV1WorkspacesApiWorkspaceControllerUpdateWorkspaceRequest
 */
export interface ApiV1WorkspacesApiWorkspaceControllerUpdateWorkspaceRequest {
    /**
     * The ID of the workspace
     * @type {string}
     * @memberof ApiV1WorkspacesApiWorkspaceControllerUpdateWorkspace
     */
    readonly id: string

    /**
     * Updated workspace data
     * @type {object}
     * @memberof ApiV1WorkspacesApiWorkspaceControllerUpdateWorkspace
     */
    readonly body: object
}

/**
 * ApiV1WorkspacesApi - object-oriented interface
 * @export
 * @class ApiV1WorkspacesApi
 * @extends {BaseAPI}
 */
export class ApiV1WorkspacesApi extends BaseAPI implements ApiV1WorkspacesApiInterface {
    /**
     * 
     * @summary Create a new workspace
     * @param {ApiV1WorkspacesApiWorkspaceControllerCreateWorkspaceRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiV1WorkspacesApi
     */
    public workspaceControllerCreateWorkspace(requestParameters: ApiV1WorkspacesApiWorkspaceControllerCreateWorkspaceRequest, options?: RawAxiosRequestConfig) {
        return ApiV1WorkspacesApiFp(this.configuration).workspaceControllerCreateWorkspace(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a workspace by ID
     * @param {ApiV1WorkspacesApiWorkspaceControllerDeleteWorkspaceRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiV1WorkspacesApi
     */
    public workspaceControllerDeleteWorkspace(requestParameters: ApiV1WorkspacesApiWorkspaceControllerDeleteWorkspaceRequest, options?: RawAxiosRequestConfig) {
        return ApiV1WorkspacesApiFp(this.configuration).workspaceControllerDeleteWorkspace(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all workspaces for the user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiV1WorkspacesApi
     */
    public workspaceControllerGetAllWorkspaces(options?: RawAxiosRequestConfig) {
        return ApiV1WorkspacesApiFp(this.configuration).workspaceControllerGetAllWorkspaces(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a workspace by ID
     * @param {ApiV1WorkspacesApiWorkspaceControllerGetWorkspaceByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiV1WorkspacesApi
     */
    public workspaceControllerGetWorkspaceById(requestParameters: ApiV1WorkspacesApiWorkspaceControllerGetWorkspaceByIdRequest, options?: RawAxiosRequestConfig) {
        return ApiV1WorkspacesApiFp(this.configuration).workspaceControllerGetWorkspaceById(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a workspace by ID
     * @param {ApiV1WorkspacesApiWorkspaceControllerUpdateWorkspaceRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiV1WorkspacesApi
     */
    public workspaceControllerUpdateWorkspace(requestParameters: ApiV1WorkspacesApiWorkspaceControllerUpdateWorkspaceRequest, options?: RawAxiosRequestConfig) {
        return ApiV1WorkspacesApiFp(this.configuration).workspaceControllerUpdateWorkspace(requestParameters.id, requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }
}



