services:
  redis:
    image: redis:8.0-alpine
    container_name: infra-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - monorepo-network

  postgres:
    image: postgres:16.9-alpine
    container_name: infra-postgres
    restart: unless-stopped
    env_file:
      - ./.env.local
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - monorepo-network

networks:
  monorepo-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis-data:
    driver: local
