import { BaseWorkflow, MessageDocument, Transition, Workflow } from '@loopstack/common';
import { GitAddTool, GitCommitTool, GitLogTool, GitStatusTool } from '@loopstack/git-module';
import { WriteTool } from '@loopstack/remote-client';

@Workflow({
  title: 'Git - Commit Flow Example',
  description:
    'Scripted multi-tool git workflow: write test file → status → add → commit → log. Demonstrates composing tools without an LLM or agent loop.',
})
export class GitCommitFlowExampleWorkflow extends BaseWorkflow {
  constructor(
    private readonly write: WriteTool,
    private readonly gitStatus: GitStatusTool,
    private readonly gitAdd: GitAddTool,
    private readonly gitCommit: GitCommitTool,
    private readonly gitLog: GitLogTool,
  ) {
    super();
  }

  @Transition({ to: 'file_written' })
  async writeTestFile() {
    const stamp = new Date().toISOString().replace(/[:.]/g, '-');
    const filePath = `tmp/git-commit-flow-${stamp}.txt`;
    await this.write.call({
      file_path: filePath,
      content: `Generated by git-commit-flow example at ${stamp}\n`,
    });
    this.assignState({ filePath, stamp });
  }

  @Transition({ from: 'file_written', to: 'status_checked' })
  async checkStatus() {
    const status = await this.gitStatus.call();
    await this.documentStore.save(MessageDocument, {
      role: 'assistant',
      text: `Status before commit:\n\`\`\`json\n${JSON.stringify(status.data, null, 2)}\n\`\`\``,
    });
  }

  @Transition({ from: 'status_checked', to: 'staged' })
  async stageAll() {
    await this.gitAdd.call({ files: ['.'] });
  }

  @Transition({ from: 'staged', to: 'committed' })
  async commit(state: { stamp: string }) {
    await this.gitCommit.call({
      message: `chore: example commit from git-commit-flow workflow (${state.stamp})`,
    });
  }

  @Transition({ from: 'committed', to: 'end' })
  async readBack() {
    const log = await this.gitLog.call({ limit: 1 });
    await this.documentStore.save(MessageDocument, {
      role: 'assistant',
      text: `Latest commit:\n\`\`\`json\n${JSON.stringify(log.data, null, 2)}\n\`\`\``,
    });
  }
}
